### ISSUE TITLE
Config file placement

### ISSUE THREAD

**Issue by JasonMcRay** [shadowfacts/DiscordChat#1]
Would it be possible to have the config file stored somewhere else than in config folder? For example in root minecraft folder.

Reason is, if player will add the mod or if the mod will be distributed as part of the modpack for example on FTB Launcher, the config folder is always overwritten with fresh one. That will delete the users edits in config file and players will need to re-add the information into there again.

**Comment by JasonMcRay** [comment]
Oh.. now that I am looking onto it... you are saying its sever-side only.... so players cant use it on singleplayer at all? Will that be implemented at some point?

**Comment by shadowfacts** [comment]
Yes the mod can be used in single player, however, if you're on a server, you'll want it on he server only. 

I'm not sure if I'll move the config file for 1.7.10, as it would require a surprising amount of work given my current system.

**Comment by shadowfacts** [comment]
Sorry, this would require more effort than it's worth given my current system.
