### ISSUE TITLE
No Join/Leave messages

### ISSUE THREAD

**Issue by wolfiepawz** [shadowfacts/DiscordChat#10]
Hello.

I am just testing the newest release for 1.7.10, and there are no join/leave messages from MC > Discord.

There are death messages and achievement messages, but as I said, no join/leave messages.

There are no errors in the log files either.

```
general {
    # Enable DiscordChat [default: true]
    B:enabled=true

    # Send player achievement messages to Discord [default: true]
    B:sendPlayerAchievementMessages=true

    # Send player death messages to Discord [default: true]
    B:sendPlayerDeathMessages=true

    # Send player join/leave messages to Discord [default: true]
    B:sendPlayerJoinLeaveMessages=true
}
```

**Comment by pchard** [comment]
general {
    # Enable DiscordChat [default: true]
    B:enabled=true

    # Send player achievement messages to Discord [default: true]
    B:sendPlayerAchievementMessages=true

    # Send player death messages to Discord [default: true]
    B:sendPlayerDeathMessages=true

    # Send player join/leave messages to Discord [default: true]
    B:sendPlayerJoinLeaveMessages=true

**Comment by shadowfacts** [comment]
I'm not sure what's happening. The event handler isn't being called by FML. This works fine in the 1.8.9 version :V

**Comment by canilsen** [comment]
Can confirm it's not working. All other features seems to work fine

**Comment by wolfiepawz** [comment]
Any progress?

**Comment by shadowfacts** [comment]
Nope, still completely clueless :D

**Comment by Pyrii** [comment]
I can confirm, nothing but MC>Discord messages are working. For now this is nothing but a glorfied server online indicator :+1: 

Could this have something to do with me using essentialschat/mcmmo?

**Comment by smbarbour** [comment]
I have found the issue.  The Join/Leave events are in FML's event bus rather than Forge's event bus.  You need to FMLCommonHandler.instance().bus().register() it separately.

**Comment by shadowfacts** [comment]
This is now working on 1.7.10 in the rewrite.
