### ISSUE TITLE
!exec permissions.

### ISSUE THREAD

**Issue by NiyahVE** [shadowfacts/DiscordChat#101]
Brief explanation of issue: I can't use !exec say for exemple, kill, set time, weather..

Steps to reproduce:

- Step 1 http://niyah.eu/i/75871.png
- Step 2 ??

Link to crash report/log in a [gist](https://gist.github.com):
None.
DiscordChat version: 
DiscordChat-1.7.10.jar

Minecraft version:
Forge 1.7.10 - 10.13.4.1614

Others mods:
ForgeEssentials.

I'm kinda sure ForgeEssentials take over vanilla command and I can't use them because of the permissions plugins... But how can I allow the bot to use them and not my players ?

**Comment by shadowfacts** [comment]
You have to get ForgeEssentials to not affect DiscordChat commands. This is not an issue with DiscordChat, !exec is designed to work with Vanilla, making it work with FE either requires you to configure FE differently on your end or you to report a bug to FE’s developers.
