### ISSUE TITLE
Config encoding problem

### ISSUE THREAD

**Issue by fanlan1210** [shadowfacts/DiscordChat#102]
Brief explanation of issue:
[DiscordChat.conf.zip](https://github.com/shadowfacts/DiscordChat/files/1200022/DiscordChat.zip)
DiscordChat.conf's character encoding convert to ASCII automatically every launch
This problem makes non-ASCII character(like ») can't display properly

Steps to reproduce:
- Launch Minecraft until it done
- Check DiscordChat.conf

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/fanlan1210/1ffdec05dc3dd5cc4e281de2b6a8b513
Config has converted at that time

DiscordChat version:2.2.0

Minecraft version:1.10.2

Sorry for my bad english :(

**Comment by shadowfacts** [comment]
DiscordChat doesn't change the encoding of any files. This is most likely an issue with your text editor saving the file as ASCII instead of UTF-8.

**Comment by fanlan1210** [comment]
But this issue has also happened when first run to generate the configuration file.
I made a video reproducing it
[Config encoding problem](https://youtu.be/bQ2J4n8Kkbw)

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.2.1.
