### ISSUE TITLE
Formatting?

### ISSUE THREAD

**Issue by EerieP** [shadowfacts/DiscordChat#104]
Is there a way to format color into the Discord chat?

**Comment by EerieP** [comment]
'
discordchat {
    commands {
        permission {
            commands=global
            exec=admin
            help=global
            online=global
            permission=global
            reload=admin
            roleid=global
            setPermission=admin
            tell=global
            time=global
            tps=global
            unstick=approved
        }
        prefix="!"
    }
    discord {
        channels=[---]
        server="---"
        token="---"
    }
    filter {
        filter=""
        mode=none
        stripFilter=false
    }
    format {
        # Format for a player achievement message from MC to Discord.
        # $1 will be replaced with the player's username and $2 will be replaced with the achievement
        achievement="$7$lMC $9» $r$1 has just earned the achievement §7$l$2"
        # Format applied to every command response message.
        # Used for differentiating command responses from multiple bot instances.
        # $1 will be replaced with the message
        command="$1"
        # Format for a player death message from MC to Discord.
        # $1 will be replaced with the player's username and $2 will be replaced with the death message
        death="$7$lMC $9» $r$2"
        # Format for a normal message from Discord to MC.
        # $1 will be replaced with the channel, $2 will be replaced with the sender's username, $3 will be replaced with the message, and $4 will be replaced with the MC color (e.g. §3) closest to the Discord user's color.
        fromDiscord="#$1 $9$l» $r<$4$2§f> $3"
        # Format for a private message from Discord to MC.
        # $1 will be replaced with the sender's username and $2 will be replaced with the message
        fromDiscordPrivate="$7$lDiscord $9» $r<$1> $2"
        # Format for a normal message from MC to Discord.
        # $1 will be replaced with the sender's username and $2 will be replaced with the message
        fromMC="$7$lMC $9» $r<$1> $2"
        # Format for a private message from MC to Discord.
        # $1 will be replaced with the sender's username and $2 will be replaced with the message.
        fromMCPrivate="$7$lMC $9» $r<$1> $2"
        # Format for a player join message from MC to Discord.
        # $1 will be replaced with the player's username
        join="$7$lMC $9» $r$1 joined the game"
        # Format for a player leave message from MC to Discord.
        # $1 will be replaced with the player's username
        leave="$7$lMC $9» $r$1 left the game"
    }
    relay {
        achievements=true
        deaths=true
        joinleave=true
        onlineoffline=true
    }
}
'

**Comment by EerieP** [comment]
it's a bit messy but I tried various things and it didn't work...

**Comment by shadowfacts** [comment]
Yes, use normal Minecraft [formatting codes](https://minecraft.gamepedia.com/Formatting_codes).

**Comment by EerieP** [comment]
I have tried using the normal code and it is not working for me.
