### ISSUE TITLE
Normal users (@everyone) discord chats not forwarded to the game

### ISSUE THREAD

**Issue by Skyridr** [shadowfacts/DiscordChat#105]
Brief explanation of issue:
@everyone chats are not being forwarded to the game, while everyone that is in a rank/role on discord, are.

Steps to reproduce:

Say something as @everyone role (no role/no color), and it should say the same.

Link to crash report/log in a [gist](https://gist.github.com):
No idea how to use gist with filenames, so created pastebin with the console errors:

https://pastebin.com/PvWCNfSy

DiscordChat version:
DiscordChat-1.7.10-2.2.1.jar

Minecraft version:
1.7.10

**Comment by shadowfacts** [comment]
c3aa74c9a8ecaadfa7c26f63b3f508ef2ebcb04c
