### ISSUE TITLE
Change of Server Token/Channel Name

### ISSUE THREAD

**Issue by janagyjr** [shadowfacts/DiscordChat#108]
Brief explanation of issue:
I updated DiscordChat to the latest, changed the name of the channel in Discord and in the configs, updated the server token, and now it throws a game-crashing/server-stopping exception.

Steps to reproduce:

- Step 1
Update DiscordChat
- Step 2
Change Channel Name in config and in Discord
- Step 3
Change bot token

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/janagyjr/d6f6677c2fba43ce320d8cfda13842a0

DiscordChat version:
2.2.1

Minecraft version:
1.7.10

**Comment by shadowfacts** [comment]
The server ID in your config file is incorrect.
