### ISSUE TITLE
People with default color on names does not get chat relayed

### ISSUE THREAD

**Issue by tjsd** [shadowfacts/DiscordChat#109]
Brief explanation of issue:
One of the fellow admins called Xavion does not get his chat relayed to the server. No other person has this issue only him. And it happens on both 1.12 and 1.7.10

Steps to reproduce:
- Step 1
Be Xavion
- Step 2
Try to chat to people ingame from discord
- Step 3 
be sad since the chat wont show up ingame

Link to crash report/log in a [gist](https://gist.github.com):
http://pastebin.ubuntu.com/25519771/
- I dont know its related, but this keeps showing up in console

DiscordChat version:
DiscordChat-1.12-2.2.1.jar 
DiscordChat-1.7.10-2.2.1.jar

Minecraft version:
1.12.1
1.7.10

**Comment by Xavion3** [comment]
We did some investigation, the error led us to a cause. It seems to be that it fails with the linked error if the user doesn't have a colour set, I was just the only person trying to chat that didn't have a role with a specific colour.

Ok, found the relevant code. [Here](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/entities/Member.java#L122-L130) is the JDA code, [here](https://github.com/shadowfacts/DiscordChat/blob/rewrite/core/src/main/java/net/shadowfacts/discordchat/core/Listener.java#L52) is the DiscordChat code. `GetColor` returns null if the user has the default color, which causes this error.

**Comment by joflashstudios** [comment]
Is there a workaround for this?
