### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by wolfiepawz** [shadowfacts/DiscordChat#11]
Hi. I have a few requests.

Is it possible to add so you can change color on the tag from MC > Discord?

Like..

&b[Discord] >&f user message

Also, a console channel wouldn't be too bad ;)

**Comment by shadowfacts** [comment]
You can already use all [Minecraft formatting codes](http://minecraft.gamepedia.com/Formatting_codes) in message formats that are going to be applied to messages from Discord to MC.

![](https://aww.moe/wge6hz.png)
