### ISSUE TITLE
Easier setup for clients

### ISSUE THREAD

**Issue by HendrikJ79** [shadowfacts/DiscordChat#110]
Complete the setup for clients who don't understand the hard way for the actual setup.
There is no way to setup by using the MC chat or the Mod Options!
As a modpack developper I cannot this mod getted working with a Singleplayer world, getting several error messages during loading the world, I have followed the instructions for the setup.

**Comment by shadowfacts** [comment]
Follow the [instructions](https://rtfm.shadowfacts.net/discord-chat/setup/) and use the config file.

Chat commands: No, this introduces way more unnecessary code complexity.
Options GUI: No, this would require a client-side mod.
