### ISSUE TITLE
DiscordChat doesn't support Discord's new Channel Categories

### ISSUE THREAD

**Issue by SalmonSays** [shadowfacts/DiscordChat#112]
Brief explanation of issue:
The bot does not appear to have support for Discord's new Channel Categories. It appears online in the sidebar, but does not relay any text to or from the servers.

Steps to reproduce:
- Step 1
Configure DiscordChat as instructed in setup
- Step 2
Create a channel category and place the configured text channel inside the category

DiscordChat version: **DiscordChat-1.12-2.2.1**

Minecraft version: **1.12.1**

Discord version: **Canary**

**Comment by Krysinski** [comment]
Same issue, also without channel category for configured text channel.
Minecraft version: 1.7.10
But, mod works if remove all categories from server!

**Comment by Thutmose** [comment]
here is the relevant error if it helps any:
https://gist.github.com/Thutmose/9a6f9945977ee0f353a3d7e4209d8451

**Comment by Morpheus1101** [comment]
What change is needed config side for this to now work?
