### ISSUE TITLE
Messages from Discord to MC not displaying in Game

### ISSUE THREAD

**Issue by ajwalters95** [shadowfacts/DiscordChat#113]
Hello,
Chat from MC to Discord works flawlessly but chat from Discord to MC is not working for me. When a message is written in Discord, discordchat spits out a few lines in the server console. Server does not crash 

Steps to reproduce:

- Write message in Discord
- View MC server console

https://gist.github.com/ajwalters95/b0567188328984e7b3836db355d08260

DiscordChat version: DiscordChat-1.12-2.2.1.jar

Minecraft version: 1.12.1

**Comment by ajwalters95** [comment]
Upon further investigation this is the same problem as Issue #109

**Comment by shadowfacts** [comment]
db8d4c07c0fe8a32747a34ecdf9d2e5d0e2a8d34
