### ISSUE TITLE
[1.12.2] New Channel Category's in Discord Breaks Relay both ways

### ISSUE THREAD

**Issue by Morpheus1101** [shadowfacts/DiscordChat#114]
With the new chat organisation system Discord has introduced, the bot i have no longer relays messages to or from discord//mc

**Comment by scalda** [comment]
i am also having this problem in the 1.10.2 version that it freezes up the server or I get a crash report [crash report](https://pastebin.com/uLgPqxhd)

**Comment by OrdinatorStouff** [comment]
snippets from 1.12.1 server log that possibly identify fault: https://gist.github.com/OrdinatorStouff/42805319c2f8352a8aa64a34c0f2c659

**Comment by Krysinski** [comment]
same on 1710! After updating mod to last version server start up without hangs.

**Comment by Krysinski** [comment]
https://github.com/shadowfacts/DiscordChat/issues/112
