### ISSUE TITLE
Bot Connected to Discord Community, Not Relaying

### ISSUE THREAD

**Issue by janagyjr** [shadowfacts/DiscordChat#116]
Brief explanation of issue:
Bot isn't relaying MC chat to/from Discord server

Steps to reproduce:

- Step 1
Install Discordchat 2.3

- Step 2
Gen new configs

- Step 3
Load new configs

- Step 4 
restart server

Link to crash report/log in a [gist](https://gist.github.com):
No crash report persay
https://gist.github.com/janagyjr/91b1b8402776ab30af8f69f954245d5c

DiscordChat version:
2.3
Minecraft version:
1.7.10

Forge:
1614

**Comment by LynSisCZ** [comment]
@shadowfacts why you closed ? I have the same problem :/

**Comment by janagyjr** [comment]
It's happening despite correct setup. DiscordChat causes DiscordBot to come online but chat is not relayed (so bot token is set correctly and channel and server id's are set properly as it's all a matter of copy/paste now).

**Comment by SevenChords** [comment]
Have the same issue, please post how this was fixed @shadowfacts
