### ISSUE TITLE
Server Fails to launch

### ISSUE THREAD

**Issue by LabGoblin** [shadowfacts/DiscordChat#12]
i get this 
http://pastebin.com/KNCjuYs2
when i try to start the server with this mod installed and hopefully properly configed

**Comment by shadowfacts** [comment]
Fixed in 1.0.1 (pending CurseForge approval).

**Comment by LabGoblin** [comment]
awesome thanks

**Comment by shadowfacts** [comment]
Wait, nevermind, there's another issue. Will fix tomorrow.

**Comment by LabGoblin** [comment]
in that case Thanks in advance

**Comment by shadowfacts** [comment]
Fixed in 50d221b6b50120b1f34cfc534018cec4e6fa5ff6.

**Comment by shadowfacts** [comment]
Fixed in 1.0.2, currently pending approval on CurseForge.
