### ISSUE TITLE
[Documentation] Numeric channel ID instead of channel name

### ISSUE THREAD

**Issue by faeldray** [shadowfacts/DiscordChat#120]
Brief explanation of issue:

Not an issue with the mod itself (it works fine), just the fact that the documentation needs to be updated to reflect the fact that the channel ID is needed instead of the channel name. Trying to use the channel results in the following error:

[10:23:11] [Server thread/ERROR] [FML/]: Caught exception from discordchat (java.lang.RuntimeException: Unable to get channel IDs, update the config to use numeric channel IDs.)

DiscordChat version: 2.3.0

Minecraft version: 1.11.2

**Comment by shadowfacts** [comment]
Read the [changelog](https://minecraft.curseforge.com/projects/discordchat/files/2488804).
