### ISSUE TITLE
Discord disabling on startup Forge 11.15.1.1739

### ISSUE THREAD

**Issue by BrewingCoder** [shadowfacts/DiscordChat#16]
[fml-server-latest.zip](https://github.com/shadowfacts/DiscordChat/files/134722/fml-server-latest.zip)

**Comment by shadowfacts** [comment]
Can you test with [this version](https://drive.google.com/file/d/0B9hnFdFvv6oGOGhycXBQTVZHYlE/view?usp=sharing)?

**Comment by MrIngelborn** [comment]
Having the same problem with both 1.0.2 and 1.0.4. 1.0.3 works fine though!

**Comment by shadowfacts** [comment]
This should be fixed in the rewrite, everything is now relocated to prevent version conflicts.
