### ISSUE TITLE
Server crash on join a player

### ISSUE THREAD

**Issue by Tander** [shadowfacts/DiscordChat#17]
[crash-2016-02-19_17.55.22-server.txt](https://github.com/shadowfacts/DiscordChat/files/138164/crash-2016-02-19_17.55.22-server.txt)

But in client it works cool, thanks =) Hope you fix this soon.

**Comment by shadowfacts** [comment]
The server ID you specified in the config is invalid.

**Comment by Tander** [comment]
So why exactly this config works perfectly in client? Messages are sensing correctly in both directions, but server id is wrong?

**Comment by shadowfacts** [comment]
Are you using the same version of the mod on both client and server? This crash should either happen on both sides or not at all.

**Comment by Tander** [comment]
> Are you using the same version of the mod on both client and server?

Yes.

> This crash should either happen on both sides or not at all.

I had server-only crash on 1.8.9 before, and author of this mod fixed it. Trying to remember what mod it was... Oh yes, that ticket: https://github.com/bdew/pressure/issues/58
Hope it helps.

**Comment by shadowfacts** [comment]
The other crash is completely different. 

I can add a check to safeguard against that crash, however there's is something on your server causing a problem. The code is identical on the server and client. If it crashes on the server it will crash on the client and if it crashes on the client then it will crash on the server.

**Comment by Tander** [comment]
I can zip and send test server to you if it helps. IDK, maybe it's client (because crash happens on join a player).

**Comment by shadowfacts** [comment]
If you can zip up both the client and server packs so I can test, that would be helpful.

**Comment by DestinyPlayer** [comment]
http://pastebin.com/h273rzkE
I seem to have the same problem as well. What's the correct way of specifying the channel, anyway? I've tried several things, and it always crashes.

EDIT: I think I figured it out. But it doesn't transfer any messages to Discord.

**Comment by shadowfacts** [comment]
You should use the name of the channel without the leading #

**Comment by DestinyPlayer** [comment]
The problem was that I placed it wrongly. I had a linebreak before the server name because otherwise it looked ugly. But it still refuses to transfer any messages, even though at least the server launched.

**Comment by shadowfacts** [comment]
Can you pastebin the entire fml-client-latest.log file?

**Comment by DestinyPlayer** [comment]
Nope, it's too long and doesn't fit into Pastebin. I uploaded it to Dropbox instead.
FML Client Log - https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/DiscordChat%20Problem.log
And in case you need it:
FML Server Log - http://pastebin.com/J1PW3bQk

**Comment by shadowfacts** [comment]
```
[00:17:34] [Server thread/ERROR] [FML/DiscordChat]: An exception occurred while loading config file DiscordChat.cfg. This file will be renamed to DiscordChat.cfg_20160306_001734.errored and a new config file will be generated.
[00:17:34] [Server thread/INFO] [STDERR/DiscordChat]: [net.minecraftforge.common.config.Configuration:<init>:118]: java.lang.RuntimeException: Malformed list property "/config/shadowfacts/DiscordChat.cfg:6"
```

Can you pastebin `config/shadowfacts/DiscordChat.cfg_20160306_001734.errored`?

**Comment by DestinyPlayer** [comment]
http://pastebin.com/2MzEAnRD
Deleted some stuff due to it being one of my actual emails, but everything of importance is still there.

**Comment by shadowfacts** [comment]
Hmm, try replacing

```
S:channels <minecraft-server-chat
     >
```

with

```
S:channels <
        minecraft-server-chat
     >
```

**Comment by DestinyPlayer** [comment]
That's what I was doing before. It kept on crashing the server the moment anybody logged in.

**Comment by shadowfacts** [comment]
Are you 200% sure that's the name of the channel? Even the case is the same?

**Comment by Tander** [comment]
BTW, version 1.3 works great, so i'm using it on my server right now.

**Comment by DestinyPlayer** [comment]
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/Sure.png
Yep, completely sure. But I'm still yet to test the new version, so I dunno if it will work.
EDIT: No, wait, I do have the newest version. So the problem's still standing.
