### ISSUE TITLE
JSONObject["muted_channels"] not found. (1.7.10)

### ISSUE THREAD

**Issue by canilsen** [shadowfacts/DiscordChat#18]
After one of the recent updates to discord, I am getting this error on startup, resulting in server halt:

http://pastebin.com/fV4UfWqw

I've been trying it on two separate servers, and against two different server id's for testing. All results in same error.
I also tested with a fresh discord account, as seen here:

http://pastebin.com/bymNdz2t

Same result. So that is same error with two different minecraft servers, two different discord servers, and two different discord accounts.

**Comment by shadowfacts** [comment]
Can you test with [this version](https://drive.google.com/file/d/0B9hnFdFvv6oGOGhycXBQTVZHYlE/view?usp=sharing)?

**Comment by canilsen** [comment]
This is for 1.7.10.

I tested your link anyway, and it doesn't load. Only mention in the logs is this:

`[16:27:47] [Server thread/INFO] [FML/]: FML has found a non-mod file DiscordChat-1.8.9-1.0.3.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.`

**Comment by shadowfacts** [comment]
Oh whoops, lemme build a 1.7.10 version with that fix.

**Comment by shadowfacts** [comment]
[1.7.10 version with fix](https://drive.google.com/open?id=0B9hnFdFvv6oGZDFHYjdrbk9JZFE)

**Comment by canilsen** [comment]
http://pastebin.com/Vj9QZeV8

Crashes

**Comment by shadowfacts** [comment]
Try [this version](https://drive.google.com/file/d/0B9hnFdFvv6oGNUZ4VDY3ZTIwc1E/view?usp=sharing)

**Comment by canilsen** [comment]
new crash:

http://pastebin.com/Svdhkyc7

**Comment by shadowfacts** [comment]
Gah, try [this one](https://drive.google.com/file/d/0B9hnFdFvv6oGbUdna2Y4TklOdUk/view?usp=sharing)

**Comment by canilsen** [comment]
It works! 

http://media1.giphy.com/media/11x4WadFj5YdZS/giphy.gif

**Comment by awade33** [comment]
Just want to add that in this version and the one we were using, neither showed the message of players logging in or out. It did show deaths and achievements though.

**Comment by shadowfacts** [comment]
@canilsen woohoo :D

@awade33 Yeah, this is a known bug (see #10), I have no clue what's causing it though :V

**Comment by kuroodo** [comment]
Hey, what was the issue causing this? I am having this same problem, but with the jDiscord API.

**Comment by shadowfacts** [comment]
@kuroodo  ¯_(ツ)_/¯ I fixed it by updating to the latest version of JDA. You can try update jDiscord and if that doesn't work, ask the dev, I guess.
