### ISSUE TITLE
Unexpected Json-parse error

### ISSUE THREAD

**Issue by Mohron** [shadowfacts/DiscordChat#19]
Hi, I've been using the 1.7.10 version of discord chat on our server for a while but just a week or so ago it stopped working and was preventing the server from starting. The linked pastebin was in the console. I tried re downloading the mod as well as resetting the config and I still ended up unable to get the server to start with this mod.

[http://pastebin.com/MMk1de91](http://pastebin.com/MMk1de91)

DiscordChat version: DiscordChat-1.7.10-0.2.0

Minecraft version: forge-1.7.10-10.13.4.1614-1.7.10

**Comment by shadowfacts** [comment]
Should be fixed in 0.2.3 on CurseForge (currently pending approval).
