### ISSUE TITLE
Fails when more than 1 person is online

### ISSUE THREAD

**Issue by canilsen** [shadowfacts/DiscordChat#2]
With only 1 person on the server, everything works fine. When 2 are online nothing is sent to Discord or back. When someone writes something, this is shown in console: http://pastebin.com/LCXerEVe

**Comment by canilsen** [comment]
Scrap that. It was a Role permission issue after some fat fingered fiddlefaddle.

Good job on the mod!

**Comment by shadowfacts** [comment]
Phew, that exception was really confusing.
