### ISSUE TITLE
Emoji Behavior

### ISSUE THREAD

**Issue by Mohron** [shadowfacts/DiscordChat#20]
### Actual Behavior:
- Emojis sent in Discord create a blank message in Minecraft.
- Text that would trigger an emoji sent from Minecraft shows up as plain text in Discord.
### Expected Behavior:
- Emojis sent in Discord will revert to text on Minecraft server chat
- Text emojis sent via Minecraft will turn to actual emojis on Discord

DiscordChat version: DiscordChat-1.7.10-0.2.3
Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
In the rewrite, Emoji sent from discord are now replaced with their Unicode alias (e.g. :smile: becomes `:smile:`). Emoji aliases sent from MC (e.g. `:smile:`) are rendered as their Unicode emoji in Discord.
