### ISSUE TITLE
I'm not sure what is happening

### ISSUE THREAD

**Issue by tombaku** [shadowfacts/DiscordChat#21]
Brief explanation of issue: I have no idea what is going on however this is the only mod I'm using apart from ShadowMC
1. I generated a new forge version by downloading the installer from http://files.minecraftforge.net/ using the Recommended version of Forge for 1.8.9 (11.15.1.1722).
2. Added ShadowMC and DiscordChat to the server and ran again.
3. added Discord Login details and server and channel details to config for DiscordChat then ran server again and got this as an error at the end of the server starting process
   [DiscordChat Error.txt](https://github.com/shadowfacts/DiscordChat/files/153734/DiscordChat.Error.txt)

ShadowMC version:3.0.0

DiscordChat version:1.0.4

Minecraft version:1.8.9

Forge version:11.15.1.1722

**Comment by shadowfacts** [comment]
/me sighs, more shading problems

I'll try and take a look at it tonight, not sure if I'll be able to do anything about it until the weekend though. Sorry.

**Comment by tombaku** [comment]
That's OK i wasn't expecting anything to happen immediately just thought id bring it to your attention

**Comment by shadowfacts** [comment]
@tombaku Can you test with version 1.0.5 on CurseForge (currently pending approval).

**Comment by tombaku** [comment]
It seems to work as shown here: 
1. this was my first go i hadn't connected with a client yet this is just from the command-line [latest.txt](https://github.com/shadowfacts/DiscordChat/files/162179/latest.txt)
2. I connected a client and it got the chat to Minecraft and discord [latest2.txt](https://github.com/shadowfacts/DiscordChat/files/162194/latest2.txt)

however it throws this crash report out as well
from 1. with no connected client [crash-2016-03-07_21.43.06-server.txt](https://github.com/shadowfacts/DiscordChat/files/162180/crash-2016-03-07_21.43.06-server.txt)

from 2. when client is attached [crash-2016-03-07_21.57.09-server.txt](https://github.com/shadowfacts/DiscordChat/files/162184/crash-2016-03-07_21.57.09-server.txt)
however the server keeps going and the chat is relayed

thought you might want to have this no clue if it helps and but it also might help to put on the curse forge page that twitch sub emote don't work inside this mod? as i think at one point it throws like a database error 
[fml-server-latest.txt](https://github.com/shadowfacts/DiscordChat/files/162198/fml-server-latest.txt)
