### ISSUE TITLE
Crash on server start up

### ISSUE THREAD

**Issue by DestinyPlayer** [shadowfacts/DiscordChat#23]
http://pastebin.com/AcazXY5v - Crash Report
http://pastebin.com/vd8UsHfN - FML Log
11.15.1.1722 - Forge Version

Not sure what is happening, but it crashes the server. When I remove it, the server launches perfectly.

**Comment by shadowfacts** [comment]
[ShadowMC](http://minecraft.curseforge.com/projects/shadowmc) is required.

**Comment by KlutzLament** [comment]
That should be made clear on the CurseForge page.

**Comment by shadowfacts** [comment]
You mean like this:

![screen shot 2016-03-09 at 5 51 44 pm](https://cloud.githubusercontent.com/assets/7091588/13653468/fda0d67a-e61f-11e5-97ed-646b6f3f2528.png)

**Comment by KlutzLament** [comment]
Hmm... I didn't realize that page existed. I always assumed the link did the same thing as the download button.
