### ISSUE TITLE
Clients are required to install shadowmc

### ISSUE THREAD

**Issue by Boingboingsplat** [shadowfacts/DiscordChat#25]
It seems like somewhat of an oversight to require clients connecting to servers with DiscordChat installed to install shadowmc, when no other mods that require it are present.

DiscordChat version: 1.0.5

Minecraft version: 1.8.9

**Comment by cauliflower69** [comment]
Having a similar issue with the 1.9 version. We really want to use the mod but for packs we don't make it's a pain to try and get users to add it. Can this requirement be removed?

**Comment by Eufranio** [comment]
Already fixed?

**Comment by Goofyschooler** [comment]
@shadowfacts is this fixed by chance? Can't seem to get mine to join my Client server

**Comment by shadowfacts** [comment]
Not yet. A temporary solution is to simply install ShadowMC on the client, it shouldn't cause problems with anything else.

**Comment by shadowfacts** [comment]
ShadowMC is no longer depended on in the rewrite.
