### ISSUE TITLE
Achievement Message Error 1.9

### ISSUE THREAD

**Issue by nemesisx00** [shadowfacts/DiscordChat#26]
Brief explanation of issue:

Unlocking an achievement causes an error at which point both DiscordChat and Minecraft achievements cease to function. I only tested this in singleplayer mode. Normal chat and leave/join messages worked fine.

Steps to reproduce:
- Set B:sendPlayerAchievementMessages=true in the configuration file
- Load into a new singleplayer world
- Open  your inventory to unlock the first Minecraft achievement
- Errors appear in the log, the achievement is not actually unlocked.
- DiscordChat is now non-functional. Achievements can no longer be unlocked.

---

Link to crash report/log in a [gist](https://gist.github.com): https://gist.github.com/Nemesis-Xero/4e4bde324ebb9c2328c073f00b23f363

DiscordChat version: 1.1.0

Minecraft version: 1.9

Forge version: 12.16.0.1816

**Comment by shadowfacts** [comment]
/me sighs, even more damn Forge event changes

**Comment by shadowfacts** [comment]
2e980b885fc66a453be132f8982d17c8b773db23.

http://minecraft.curseforge.com/projects/discordchat/files/2291482 (currently pending approval)
