### ISSUE TITLE
Death Message Crash 1.9

### ISSUE THREAD

**Issue by nemesisx00** [shadowfacts/DiscordChat#27]
Brief explanation of issue:

With the death message functionality enabled, the game crashes shortly after joining.
I only tested this in singleplayer mode. Normal chat and leave/join messages worked fine.

Steps to reproduce:
- Set B:sendPlayerDeathMessages=true in the configuration file
- Load into a singleplayer world
- As the world loads, the game will eventually crash.

---

Link to crash report/log in a [gist](https://gist.github.com): https://gist.github.com/Nemesis-Xero/67ee664957ec6a9e99a103efd41d40c6

DiscordChat version: 1.1.0

Minecraft version: 1.9

Forge version: 12.16.0.1816

**Comment by shadowfacts** [comment]
2e980b885fc66a453be132f8982d17c8b773db23.

http://minecraft.curseforge.com/projects/discordchat/files/2291482 (currently pending approval)
