### ISSUE TITLE
CloudFlare Preventing Server from Launching with Account Information Correct

### ISSUE THREAD

**Issue by MastaC729** [shadowfacts/DiscordChat#29]
Brief explanation of issue:

My listener account for our server seems to being labeled as an unauthorized bot. It now receives CloudFlare pages asking to complete a captcha, disabling the mod when the mod cannot connect to the server with the listener account after enough tries.

Steps to reproduce:
- Step 1: Create an account specifically for relaying messages to Discord.
- Step 2: After enough time, it seems that the Discord's server's CloudFlare support is labeling my listener account as a threat. When this happens, it prints an html file into the log (see link below).

Link to the log information: http://pastebin.com/7dG16MEj

DiscordChat version: 1.0.5

Minecraft version: Forge 1.8.9-11.15.1.1855

NOTE: I have verified that the login information is correct several times now. It must be something that fails after the login attempts fail, otherwise I would still be fixing the borked password.

**Comment by shadowfacts** [comment]
My guess is this is because of the introduction of the official API, the unofficial one will be phased out soon. DiscordChat will soon be updated to use the latest version JDA which uses the official Discord API.

**Comment by shadowfacts** [comment]
Should be fixed with the updates for the official API. The latest 1.8.9 version is 1.0.8.
