### ISSUE TITLE
Chat tag options

### ISSUE THREAD

**Issue by Towsty** [shadowfacts/DiscordChat#3]
Works great, really happy with this mod overall! One question, would it be possible to have the tag that is used when messages are sent to be configurable in the future? So instead of it saying, in my case, MC >> <username> message. Could the "MC >>" configurable (ie. Bot: username message, or Server x: username message). That way if we have more than one server we could use the same bot to bridge between the discord and the servers and still distinguish between the different servers

**Comment by shadowfacts** [comment]
Yes, this is definitely coming for the 1.8.9 version, possibly the 1.7.10 version.
