### ISSUE TITLE
[Suggestion] Use Bot Tokens

### ISSUE THREAD

**Issue by Eufranio** [shadowfacts/DiscordChat#34]
Would be cool if the mod use Bot Tokens. My server is running 1.8.9 forge minecraft.

**Comment by shadowfacts** [comment]
I'm currently in the middle of update the 1.8.9 and 1.9 versions of the mod to use the official API.

**Comment by shadowfacts** [comment]
f13533adafc101f1a85ba4893e955b3fa40641e6.

Version 1.0.7 for MC 1.8.9 has been uploaded to CurseForge and is pending approval.

**Comment by Eufranio** [comment]
You could post "pre" versions in the /releases here in github...
