### ISSUE TITLE
[Asking] Really needed?

### ISSUE THREAD

**Issue by Eufranio** [shadowfacts/DiscordChat#35]
Why do I need to put e-mail and password in the mod config, even if i have a Bot Token?

**Comment by shadowfacts** [comment]
Are you using the latest version of DiscordChat?

**Comment by Eufranio** [comment]
Yes, for 1.8.9.

**Comment by shadowfacts** [comment]
You should be able to safely delete the entries from the config, they aren't used anymore. The entries in the config file are left over due to the way Forge's config system works.
