### ISSUE TITLE
High tps when running discordchat mod

### ISSUE THREAD

**Issue by Saereth** [shadowfacts/DiscordChat#37]
Brief explanation of issue:When running this mod on the revolution 2 pack for 1.7.10 we're getting massive TPS increases from the mod. here is a screenshot of opis
http://imgur.com/Z64rIIq

Steps to reproduce:
- Step 1
  Install Revolution2 pack from ATlauncher with default mod selection
- Step 2
  add discord mod to the server and boot, after the server runs for a while tps will continually climb until you restart. 

Link to crash report/log in a [gist](https://gist.github.com):

DiscordChat version:
DiscordChat-1.7.10-0.3.0

Minecraft version:
1.7.10

**Comment by shadowfacts** [comment]
1. 1.7.10 is no longer supported.
2. Discord API calls may be blocking which could cause this. If this is the case it will be fixed for 1.8.9+

**Comment by shadowfacts** [comment]
All Discord interaction now happens in a separate thread, which should fix this.
