### ISSUE TITLE
From discord messages does not appear ingame

### ISSUE THREAD

**Issue by ghost** [shadowfacts/DiscordChat#38]
Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/TheColher/acc50ed608641fa9c9b6749f6790e351

DiscordChat version: 0.3.0

Minecraft version: 1.7.10

**Comment by Eufranio** [comment]
1.7.10 is no longer supported.

**Comment by shadowfacts** [comment]
1.7.10 is supported, but only for major bugs (such as this one).

**Comment by Cyahnide** [comment]
What makes a bug major to be supported for 1.7.10?
Because this issue 
https://github.com/shadowfacts/DiscordChat/issues/37
Seems pretty big to me. It's almost unusable with this insane TPS spikes every few seconds.

**Comment by shadowfacts** [comment]
This mod exists for 4 different versions of Minecraft, with the same bugs needing to be fixed for all of them. At some point I have to draw the line. I'm moving closer and closer to just dropping support for 1.7.10.

**Comment by ArukaAlter** [comment]
![](https://i1.someimage.com/UrhmIHP.png)
![](https://i1.someimage.com/WKs8yTy.png)
The problem only appears if the mod is loaded in an integrated server (local worlds).
DiscordChat 1.2.2 for 1.9.4

**Comment by shadowfacts** [comment]
Unable to reproduce.

![screen shot 2016-06-20 at 10 02 03 am](https://cloud.githubusercontent.com/assets/7091588/16196961/12194d68-36ce-11e6-88fc-cf7777898cc1.png)

**Comment by ghost** [comment]
have you tested this in 1.7.10?

**Comment by shadowfacts** [comment]
1.7 is no longer supported. 

A) It was released 3 years ago, get with the times.
B) I can't maintain the mod concurrently for 5 different versions of Minecraft, 1.7 being the oldest, I no longer support it.
