### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by coleweinman** [shadowfacts/DiscordChat#39]
When I join the server, it crashes and on the client, it says "Internal server error"

Crash Report: http://pastebin.com/14rdxKaz

Config: http://pastebin.com/w12mBQTG

DiscordChat version: 0.3.0

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
Is DiscordChat disabled? If so just remove it from the server, there's a bug in the 1.7 version.

If it's enabled then it can't connect to Discord. Check your credentials in the config.

**Comment by coleweinman** [comment]
@shadowfacts What do you mean is it disabled, isn't it running if it crashed like that?

**Comment by coleweinman** [comment]
@shadowfacts in the config it says it is enabled, and I checked all of the config values and they are correct.

**Comment by shadowfacts** [comment]
Post the entire log.

**Comment by coleweinman** [comment]
@shadowfacts  Ok it's huge
[fml-server-latest.zip](https://github.com/shadowfacts/DiscordChat/files/302817/fml-server-latest.zip)

**Comment by coleweinman** [comment]
Oh wow, I figured it out. I didn't know I had to enable setup in DiscordChat.private.

Anyways thanks for the help.
