### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ArukaAlter** [shadowfacts/DiscordChat#40]
DiscordChat crashes after being configurated.

Steps to reproduce:
- Set up the bot's required configurations (token and server id)
- Launch the game

http://pastebin.com/BGNYVy2z

DiscordChat-1.9.4-1.2.0

Minecraft 1.9.4

**Comment by shadowfacts** [comment]
What version of Forge are you using?

**Comment by ArukaAlter** [comment]
Forge 1.9.4-12.17.0.1962 as listed in the log, but for some reason DiscordChat 1.2.1 loads fine (and isn't on Curse yet).

**Comment by shadowfacts** [comment]
1.2.1 is available on Curse.

![screen shot 2016-06-13 at 3 17 39 pm](https://cloud.githubusercontent.com/assets/7091588/16020001/fccb432a-3179-11e6-91ef-02527a20a6d9.png)

**Comment by ArukaAlter** [comment]
![](http://image.prntscr.com/image/ecf39c6e541b4baa99a474e9f833fecd.png)
The file isn't being listed right now, but it's showing as valid in the mod list.

![](http://image.prntscr.com/image/154ddb19a3e14e62adf58ae0cd597219.png)

Solved for now. Closing?

**Comment by shadowfacts** [comment]
I have no idea, this is likely a problem with the Curse app and you should report it to them.

**Comment by shadowfacts** [comment]
Can you try this version? https://drive.google.com/file/d/0B9hnFdFvv6oGWHU2MU1mdEQwS1U/view?usp=sharing

**Comment by ArukaAlter** [comment]
I know that the Curse app takes too much time to update the file list.
The crash was indeed fixed in 1.2.1
1.2.2 behaves normal
