### ISSUE TITLE
Impossible to add bot user to server.

### ISSUE THREAD

**Issue by Tander** [shadowfacts/DiscordChat#41]
{REDACTED}

saying "unknown_error"
So i can't even try DiscordsChat.

**Comment by shadowfacts** [comment]
Did you follow these instructions? https://gist.github.com/shadowfacts/2df3ecc50b8fd07e8113130affd9619d

**Comment by Tander** [comment]
Yes. Can you check that instruction still corect? Because I suppose step 8 is not.

**Comment by shadowfacts** [comment]
The instructions are still completely correct, I just went through them from scratch.

You made a mistake somewhere.
