### ISSUE TITLE
[Server 1.9.4 Crash]

### ISSUE THREAD

**Issue by APolarBaer** [shadowfacts/DiscordChat#42]
Brief explanation of issue:

Steps to reproduce:
- Step 1 finally got it connecting
- Step 2 log in as a player

Link to crash report/log in a [gist](https://gist.github.com):

http://pastebin.com/BpfEY1rj

DiscordChat version:
1.2.0
Minecraft version:
1.9.4

**Comment by APolarBaer** [comment]
updated to the version 1.2.2 i found and it doesnt crash.
wish curse would show 1.2.1 even

thought i was latest, my apologies

**Comment by shadowfacts** [comment]
Yeah, the Curse client is wonky with mod versions, AFAIK there's nothing I can do about it though :V

**Comment by APolarBaer** [comment]
for some reason it wont send the messages from discord to my dedicated hosted server, but it will to the server i run on my machine

**Comment by APolarBaer** [comment]
http://pastebin.com/SL2H2DYr

and now im not getting anything but login messages and this on the console when i go from discord to mc
