### ISSUE TITLE
config file struggle

### ISSUE THREAD

**Issue by RebeccaRedstone** [shadowfacts/DiscordChat#43]
Brief explanation of issue: I have updated the default config multiple times and it is still not linking to my discord chat. :(
I think it has to do with the part     

```
# Channels that should be forwarded to MC/MC be forwarded to.
# (Without the # at the beginning)
S:channels  <

 >
```

so I changed it to this;

```
# Channels that should be forwarded to MC/MC be forwarded to.
# (Without the # at the beginning)
S:channels=uk
```

Now I am not getting the error config - but it is not linking to discord :( 

Steps to reproduce:
- be like me
- update your config file and fail. 

Link to crash report/log in a [gist](https://gist.github.com):

DiscordChat version: 1.9-1.1.5

Minecraft version: 1.9 
 forge-1.9-12.16.1.1938

any help is appreciated

**Comment by shadowfacts** [comment]
Put the name of the channel inside the `<` and `>`

**Comment by RebeccaRedstone** [comment]
```
Like this?

# Channels that should be forwarded to MC/MC be forwarded to.
# (Without the # at the beginning)
S:channels <
unicornkingdom
 >
```

Still not working :( 

Also tried 
    # Channels that should be forwarded to MC/MC be forwarded to.
    # (Without the # at the beginning)
    S:channels < unicornkingdom
     >

and 
    # Channels that should be forwarded to MC/MC be forwarded to.
    # (Without the # at the beginning)
    S:channels <unicornkingdom>

D:

**Comment by shadowfacts** [comment]
That should work, what does it say in the log?

**Comment by RebeccaRedstone** [comment]
[17:56:41] [Server thread/TRACE] [DiscordChat/DiscordChat]: Sending event FMLServerStartingEvent to mod DiscordChat
[17:56:41] [Server thread/ERROR] [DiscordChat/DiscordChat]: DiscordChat has not been setup. Follow the instructions () and change setup to true in config/shadowfacts/private.properties
[17:56:41] [Server thread/TRACE] [DiscordChat/DiscordChat]: Sent event FMLServerStartingEvent to mod DiscordChat

that is the link that I used for setup but it does not say to change the other config to true. You should add it. :smile: 
That config appears to be called DiscordChat.private 

When I changed setup to true it didn't do anything either :( It did change my player count (as seen from the multiplayer server list to ??? )

Changed the config name to private.properties and nothing changed. 

D:

**Comment by shadowfacts** [comment]
The log message, is wrong DiscordChat.private is correct. Changing `setup` to true should fix it.
