### ISSUE TITLE
Feature request: A quick blurb when the server is online and upon shutdown 

### ISSUE THREAD

**Issue by utoc** [shadowfacts/DiscordChat#45]
Hello! 

Would it be possible to add an option so that the server announces in Discord when is online and when it's being shutdown? Additionally, is there any way for it to announce that java is crashing? I feel the last one might be pushing my luck though.

Announce: "[server name from server.properties] is now [online¦offline]" 

Thanks so much!

**Comment by shadowfacts** [comment]
This has been added in the rewrite, which will be out soon.
