### ISSUE TITLE
Crash when sacrificing myself in bloodmagic

### ISSUE THREAD

**Issue by Pndy** [shadowfacts/DiscordChat#46]
So this happens sometimes when you die sacrificing your blood in bloodmagic

Crash report: https://paste.ee/p/8p6M0 - error starts at line 3933

DiscordChat version: 1.2.1 ( I know its not the latest, but im on server + dont know if its fixed/related to changes)

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
Have you sent message to/from Discord before the crash and have the gone through successfully?

**Comment by Pndy** [comment]
I checked, and the message for "my soul becoming too weak" and me leaving the game because the crash both went to discord, so did the messages before and after my crash

**Comment by shadowfacts** [comment]
Fixed in the rewrite, which will be released soon.
