### ISSUE TITLE
Crash from Server Watchdog

### ISSUE THREAD

**Issue by utoc** [shadowfacts/DiscordChat#47]
Brief explanation of issue:

A server logged in to the server, there was no one else on at the time, and the server ended up crashing. I don't understand the technicalities of a watchdog crash any further than this.  This is also a unique crash; we have not had any others and Discord chat has been working flawlessly for 5 days now.

Link to crash report: http://pastebin.com/8qVMiaMa

DiscordChat version: 1.10.2-1.3.0
ShadowMC version: 1.10.2-3.4.4
FML Version: forge-1.10.2-12.18.1.2011-universal.jar
Minecraft version: 1.10.2

Sorry if this does not provide enough information; let me know what I have neglected.

**Comment by shadowfacts** [comment]
That's not caused by DiscordChat. That's a Minecraft/Forge crash.
