### ISSUE TITLE
[1.10.2] Discord causing server crash 

### ISSUE THREAD

**Issue by ghost** [shadowfacts/DiscordChat#50]
Brief explanation of issue:  Server will not start with Discord Chat mod enabled find it wierd as it has been working flawlessly since my modpack was started but at this stage i am unable to start the server because of discord.

Steps to reproduce:
- Step 1 start server
- Step 2 crash

Link to crash report/log in a [gist](https://gist.github.com/Stuart74/029644aeba720c86813fa2cf1e956d91):

DiscordChat version: DiscordChat-1.10.2-1.3.0

Minecraft version: 12.18.1.2014

List of Mods Installed can be seen on my Curse Project Page here [Modlist](http://minecraft.curseforge.com/projects/empyrean)

Discord Mod is not shipped with the modpack as its a server side only mod and i am not making the server files available as of yet for this pack.

**Comment by shadowfacts** [comment]
I cannot tell what is causing this as it appears that a Java thread is somehow being prevented from sleeping. Not sure if there's anything I can do about this.

**Comment by ghost** [comment]
thanks for having a look i re enabled the mod to see how it goes and seems to have rectified itself maybe it was just a one off that cleared itself when my entire server restarted.
