### ISSUE TITLE
Message duplication

### ISSUE THREAD

**Issue by Tander** [shadowfacts/DiscordChat#54]
Brief explanation of issue:
I'm type test123 in ingame chat and see this in console(SSP):
[13:22:57] [ReadingThread/INFO]: server » <elittle-bot> MC » <MrTander> test123
[13:22:57] [Server thread/INFO]: <MrTander> test123
[13:22:57] [Client thread/INFO]: [CHAT] server » <elittle-bot> MC » <MrTander> test123
[13:22:57] [Client thread/INFO]: [CHAT] <MrTander> test123
So every message from minecraft are duplicating from discord chat.

DiscordChat version:
1.4.0
Minecraft version:
1.10.2

**Comment by shadowfacts** [comment]
Are you sending the message from Discord or from MC? Can you revert back to the default message formats and see if the issue persists?

**Comment by Tander** [comment]
From MC. Message formats are default:
http://pastebin.com/B9pKASct

**Comment by shadowfacts** [comment]
You've used the wrong ID In the `botId` field of the config file. You should be using the long, numerical ID in the Bot ID section of the Discord bot page: 

![screen shot 2016-09-10 at 10 37 17 am](https://cloud.githubusercontent.com/assets/7091588/18411302/b65f6c86-7742-11e6-88c4-ea197547d24e.png)

**Comment by Tander** [comment]
http://i.imgur.com/tKEr3C7.png
I don't have this line in my bot page. Is there the same id as Client ID (using in url)?

**Comment by Tander** [comment]
Yes, it's Client ID in my case. Can you add this info to setup manual?

**Comment by shadowfacts** [comment]
No, the Client ID is not the same as the Bot ID.

**Comment by shadowfacts** [comment]
You should contact Discord and see if they know why the Bot ID isn't present on your application page.

**Comment by Tander** [comment]
But it's working just fine, no duplicated messages now. With Client ID, yes.

**Comment by shadowfacts** [comment]
o_O That's weird. Maybe something's changed with the Discord API...
