### ISSUE TITLE
Server crashing in 1.10.2 when attempting to setup discord mod

### ISSUE THREAD

**Issue by Saereth** [shadowfacts/DiscordChat#55]
Brief explanation of issue:
I created a new bot, authorized it and followed the rest of the setup instructions. The bot is able to join our channel on server start and I gave it member permissions which can speak. Discord relays into minecraft without issue, the first time someone says anything from within minecraft however it crashes the server.

Steps to reproduce:
- Step 1
  create new bot as per setup instructions, set Discord.private setup=true, start server
- Step 2
  Type anything and press enter as a player/admin from within minecraft

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/Saereth/1a571f4cde31c77c8cc40043cffb5e0b

DiscordChat version:
DiscordChat-1.10.2-1.4.0.jar

Minecraft version:
1.10.2 vanilla forge, custom pack

**Comment by shadowfacts** [comment]
You're 100% sure the bot has message sending permissions in the Discord channel you're using?

**Comment by Saereth** [comment]
Yeah just to be sure its not something I've set wrong, here are the discord settings

http://imgur.com/a/4hh5i

**Comment by Saereth** [comment]
I removed the perms other than member and it seems to be ok now, thanks for checking
