### ISSUE TITLE
Cross-mod compatibility with Custom NPCs

### ISSUE THREAD

**Issue by xenoflot** [shadowfacts/DiscordChat#56]
Brief explanation of issue: Dialog from NPCs created with Custom NPCs mod is being echoed in Discord

Steps to reproduce:
- Install Custom NPCs mod https://minecraft.curseforge.com/projects/custom-npcs
- Create some NPCs (default settings plus "wander", a custom name and skin from a player name, no other changes)
- NPCs will periodically say "........."  (I think this is when they interact with other NPC)
- This text appears as if spoken by a player in game. <Xenobot> .........

I haven't gotten into the dialog / interaction functions of the mod yet but noticed this after install it today.

Link to crash report/log in a [gist](https://gist.github.com): n/a

DiscordChat version: 1.10.2-1.4.0

Minecraft version: 1.10.2

Forge version: 2107

CustomNPCs version: 1.10.2_beta(10oct16)

**Comment by shadowfacts** [comment]
Closing as there's no good way to fix this without special casing for Custom NPCs (which is difficult because they don't provide source code/an API).
