### ISSUE TITLE
Nicknames not showing for Discord->Server messages

### ISSUE THREAD

**Issue by xenoflot** [shadowfacts/DiscordChat#59]
Brief explanation of issue:
My Discord username is Xenoflot. On the linked discord server, I have been given a nickname of my IGN. When I type messages in the Discord/Server channel, it shows in server chat as <Xenoflot>

DiscordChat version: 1.10.2-1.4.0

Minecraft version: 1.10.2

Forge version: 2185

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4.
