### ISSUE TITLE
Missing JDA classes

### ISSUE THREAD

**Issue by shadowfacts** [shadowfacts/DiscordChat#6]
ejmiv89:

> Gotcha then I'll need to either screenshot or try to find a log for it. What the mod does (with correctly setup config file) on the client for me, is i attempt to load a new world, and it shoots back to the main menu. (this happens with no mods [clean install] or with a pack, like Infinity) Heres the fml-client-latest http://paste.ubuntu.com/14593283/

shadowfactsdev:

> Uhm... The log says the class org.apache.http.nio.reactor.IOReactorExceptionis missing, however I see it in the compiled jar (screenshot ). I'm not sure what's going on, can you download the latest version from CurseForge and try again? The jar may have gotten corrupted :V

ejmiv89:

> Sure ill redownload it. (edit) same result with fresh download. I'm showing the files in the jar thou. http://i.imgur.com/FP6m4B4.png

shadowfactsdev

> I have no idea what's going on, then. It works on my machine™ :V

ejmiv89:

> I tried using the latest forge 1614, and 1558. or how can I recreate your situation (beyond attempting a dev environment)? I use Curse Voice Launcher (new FTB one) to run my modpacks, its been great so far, i can switch forge versions and update mods seamlessly. Pro Tip for discord users - https://www.reddit.com/r/discordapp/comments/3x1ng4/what_is_the_secret_overlay/ I have another idea, maybe could we compare download hashes? possibly that could be the difference between, a working client mod or just a server mod? In addtionm, I'm using windows 10, what Os are you using (could be a problem win10 has been for some things)

shadowfactsdev:

> Yeah, can you use something like this to calculate the md5 sum of the jar?
> The mod should work perfectly fine on both singleplayer client and multiplayer server.
> I'm using OS X, however that shouldn't make a difference.
> Also, can we switch to this GitHub issue, just so it's on the actual bug tracker and easier for me to keep track of.

**Comment by ejmiv** [comment]
maybe im not setting up the config right? Also I installed that link u gave me im not sure what it did, cause I dont see a scanner app, and do you have your checksum to base against?

Update: found a checker to use - http://download.cnet.com/MD5-SHA-Checksum-Utility/3000-2092_4-10911445.html

Heres my Checksums of a Fresh download  from CurseForge - 
MD5 Checksum: 077201C63813C89041FEFD996800DC32
SHA-1 Checksum: 9E36EEC1257E6702D2ED5D7F16077A35BCDD7327
SHA-256 Checksum: EF2C4C56F0C2B0B4BAD4B8609BD4B4D7834B266A7692C2B39852B811E82A5438
SHA-512 Checksum: 391C9ADA6276B2E7630FAF26349E361AC219618DBC04EBF4E5C315153D3C77CFCA19312A55102852EBC84BDCBD3A958C9F45122AAD815F18C653ED3723EA42E2
Generated by MD5 & SHA Checksum Utility

```
# Configuration file

discord {
    # Channels that should be forwarded to MC/MC be forwarded to.
    # (Without the # at the beginning) [default: ]
    S:channels <
        general-discussion
     >

    # The email used to login to Discord.
    # Required [default: ]
    S:email=

    # The password used to login to Discord.
    # Required [default: ]
    S:password=

    # The server ID to connect to. [default: ]
    S:serverId=138439073755824128
}


general {
    # Enable DiscordChat [default: true]
    B:enabled=true
}
```

*when I add in my email n pass like it wants, it "derps" at the loading SSP. shooting me back to the main menu, not launching the game. I have to remove my email/pass or just remove the mod for me to launch the world. I tested this now with Vanilla MC + Forge , MultiMc +Forge, and CurseVoice + Forge.

**Comment by shadowfacts** [comment]
Hmm, that is the same md5 checksum as I have, and your configuration looks fine.

**Comment by piotrb** [comment]
I've got a repro for this in a fairly clean environment .. 

Using ATLauncher, "Vanilla" modpack, with Forge latest installed

Just drop discord chat into mods, add your config .. and getting the
`[26/1/2016 17:27:25 PM] Caused by: java.lang.ClassNotFoundException: org.apache.http.nio.reactor.IOReactorException` exception ..

**Comment by piotrb** [comment]
perhaps this works for you because some other mod injects another version of that class into the classpath? .. but on this very clean setup ther's nothing there to provide it?

**Comment by piotrb** [comment]
oh yea .. this is on 1.7.10 for me

**Comment by ejmiv** [comment]
dont use the config i have there thats just an example but the issue isnt with the launcher or forge because it reproduces the same error on different forge versions and the vanilla launcher with curse and vanilla is the best launcher to test bugs with

**Comment by piotrb** [comment]
Another strange repro to throw into the mix .. 

I basically made a copy of the jar file .. nuked the mod stuff out of it .. (so classes at the root of the archive) and also shadowfacts's namespace out of there .. named it 'mc-deps.jar' and stuck it in bin/libraries/whatever is a libs path for your launcher (atlauncher seems to stick them in bin, on my server there is a libraries folder) .. 

anyways .. it worked .. so there is definitely something weird with those vendor libraries in the jar ..

**Comment by ejmiv** [comment]
vendor libs? anyway are you saying thats the launcher im using? if so lets commend on getting it working for the original minecraft launcher instead because if it works there then it should work for everyone. i know the op is on mac and i dunno why it doesnt work clientside on windows.

**Comment by shadowfacts** [comment]
I don't know if it's a launcher issue. Can you try reproducing it using the latest version of MultiMC?

**Comment by scarabcoder** [comment]
I've tried fixing this same issue for hours now. @piotrb did you end up fixing it? If so, how?

**Comment by scarabcoder** [comment]
Oh, I apologize for not giving more information. I am having the same problem with JDA and Forge when creating my own mod. I can't seem to find the problem.

**Comment by shadowfacts** [comment]
Closing as I still have no idea how to fix this (or even how it's caused). It may have inadvertently been fixed in the rewrite.
