### ISSUE TITLE
1.10.2 v2.0.0 - Server crash on startup

### ISSUE THREAD

**Issue by Boomflex** [shadowfacts/DiscordChat#60]
Brief explanation of issue: Server crash on startup running All the Mods 1.10.2 Latest Version (1.52b)

Link to crash report/log in a [Crash Report](http://pastebin.com/s5Kh63dk):

DiscordChat version: 2.0.0

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
Did you follow the [setup instructions](https://rtfm.shadowfacts.net/discord-chat/setup/)?

**Comment by Boomflex** [comment]
Yes sir, we ran the old version perfectly fine so I understand how to do it.

Just not this time it seems.

**Comment by shadowfacts** [comment]
Are you still using the old config (`config/DiscordChat.cfg`) or did you use the new one `config/DiscordChat/DiscordChat.conf`?

**Comment by Boomflex** [comment]
I deleted the mod and the configs and re-populated from fresh.
