### ISSUE TITLE
[1.11] [DiscordChat 1.11-2.0.0] NPE crash upon server load.

### ISSUE THREAD

**Issue by shortybsd** [shadowfacts/DiscordChat#61]
Crash upon server load

Steps to reproduce:

- Load on server
- Boom CRASH ... good ole NPE's

Crash - http://pastebin.com/daFJZ5VM

DiscordChat version: 1.11-2.0.0

Minecraft version: 1.11

Forge Version: 2199

**Comment by shadowfacts** [comment]
Did you follow the [setup instructions](https://rtfm.shadowfacts.net/discord-chat/setup/)?

**Comment by shortybsd** [comment]
Yes, not my first rodeo brother.

**Comment by shadowfacts** [comment]
Are you still using the old config (`config/DiscordChat.cfg`) or did you use the new one `config/DiscordChat/DiscordChat.conf`?

**Comment by shortybsd** [comment]
I generated a new one then edited those new options to reflect my old servers settings.

**Comment by shortybsd** [comment]
It crashes shortly after it creates a new config.

**Comment by shadowfacts** [comment]
Can you send me a pastebin of your config?

**Comment by Schultz** [comment]
I also am getting a NPE with 1.7.10 and Infinity modpack during startup. 
http://pastebin.com/1q4MFKiN

Though it works for me on 1.10.2 direwolf20 1.2.1 pack.

**Comment by shadowfacts** [comment]
Can you also send me a pastebin of your config?

**Comment by shortybsd** [comment]
config/shadowfacts/DiscordChat/DiscordChat.conf

http://pastebin.com/rSufCD4m

**Comment by shadowfacts** [comment]
~~Can you email me (me@shadowfacts.net) the entire config file, including the Discord connection details so I can test if it connects from my computer?~~

**Comment by shadowfacts** [comment]
Can both of you download the version of DiscordChat 2.0.2 appropriate to your MC version from [here](https://github.com/shadowfacts/DiscordChat/releases/tag/2.0.2) and try launching the server with that?

**Comment by shortybsd** [comment]
For sure, thanks will let you know here shortly.

**Comment by shortybsd** [comment]
1.11-2.0.2 works! The channel cannot be in double quotes, it fixed it upon load.
