### ISSUE TITLE
[1.7.10] Exception in server tick loop

### ISSUE THREAD

**Issue by Hastling** [shadowfacts/DiscordChat#62]
Brief explanation of issue: This is a fresh install on a Thermos server. I have previously installed and configured DiscordChat a 1.10.2 server without issue. When DiscordChat is removed the server starts up just fine.

Steps to reproduce:

- Attempt to start the server
- Experience the crash, and cry

Crash Log: http://pastebin.com/m1bVJ7gF

DiscordChat version: 1.7.10-2.0.1

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
Can you download the version of DiscordChat 2.0.2 appropriate to your MC version from [here](https://github.com/shadowfacts/DiscordChat/releases/tag/2.0.2) and try launching the server with that?

**Comment by steelshot** [comment]
I have tried, but no luck still crashing. 1.7.10 https://paste.ee/p/8dx9I

**Comment by shadowfacts** [comment]
Can you send me a pastebin of your config?

**Comment by steelshot** [comment]
This will expire after you view it

https://paste.ee/p/9ao7w

**Comment by shadowfacts** [comment]
That's not the config, that's a completely unrelated crash caused by TehNut's Launch GUI mod.

**Comment by steelshot** [comment]
god dammit, multitasking too much https://paste.ee/p/7BKm6

**Comment by shadowfacts** [comment]
I'm unable to reproduce this. Using your config on 1.7.10, DiscordChat starts and connects perfectly fine.

**Comment by steelshot** [comment]
What mod should I look(functionality of it) for, as it seems a crossmod compatibility issue?

mods that do some chat stuff:
DynMap(with Mysql(J Connector)) and Help Fixer

**Comment by steelshot** [comment]
Mods running on the server http://www.modlister.com/server/MCMineTech

**Comment by Hastling** [comment]
DiscordChat 2.0.2 for 1.7.10 still crashes on load [Crash Log](http://pastebin.com/khPFPSQd). For reference I'm using [GT New Horizons](http://www.technicpack.net/modpack/mcnewhorizons.677387) and as SteelShot mentioned I'm also using DynMap.

**Comment by shadowfacts** [comment]
Can you try removing the quotation marks from around the channel name in the config?

**Comment by Hastling** [comment]
Channel, Server, and token are currently blank but I just removed the quotations and I'm restarting now. It's not a fast process with the 3mb's of MineTweaker scripts.

**Comment by shadowfacts** [comment]
Well if you haven't [setup DiscordChat](https://rtfm.shadowfacts.net/discord-chat/setup/), of course it's not going to work >.>

**Comment by Hastling** [comment]
I have set up Discord chat, but when you made me download 2.0.2 I deleted the old config. But that's fine. I see you've already closed the issue so I will not be using your Mod.

**Comment by shadowfacts** [comment]
If you go through the setup process and it's still crashing, then tell me.

**Comment by Hastling** [comment]
The config file is set up and after numerous tests the intergration is working fine with version 2.0.2

**Comment by steelshot** [comment]
Strangely enough after 2 re-setups, it worked...
