### ISSUE TITLE
Cant Get Config file to generate 

### ISSUE THREAD

**Issue by javierapl12** [shadowfacts/DiscordChat#63]
Brief explanation of issue:
ive been trying to install the discordchat mod following the steps indicated but i cant seem to get the config to generate in my server instance neither in my client instance
Steps to reproduce:

- Step 1
- Step 2

Link to crash report/log in a [gist](https://gist.github.com): no crash log available

DiscordChat version: 2.0

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
Can you provide any more details, I'm unable to reproduce this. Using the 1.7.10 version, the config file is generated in `config/shadowfacts/DiscordChat/DiscordChat.conf`.

**Comment by shadowfacts** [comment]
Closing because no response.
