### ISSUE TITLE
Server Crashes over and over again

### ISSUE THREAD

**Issue by ToxicToast** [shadowfacts/DiscordChat#65]
Brief explanation of issue:
After editing the Conf. File with all my credentials (proofed local if it works, it worked).
Putting the Mod on my Server crashes it all over again with the same Error Message (Crash Logs appended)

Link to crash report/log in a [gist]:
https://gist.github.com/ToxicToast/419435e221804acca84d2a8ac4dbc0cf

DiscordChat version:
2.0.1

Minecraft version:
1.7.10

Modpack
Skyfactory 2.5
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-2-5

**Comment by shadowfacts** [comment]
Can you send me a pastebin of your config with the token removed?

**Comment by ToxicToast** [comment]
Here it comes!

https://gist.github.com/ToxicToast/826762527c0b7ae03a2519c209680a60

**Comment by shadowfacts** [comment]
If you run the server locally on your computer, does it work or does it still crash? How about with just DiscordChat running locally?

**Comment by ToxicToast** [comment]
It works perfect local - if i try to install the mod on a server, it crashes

**Comment by Gaelan** [comment]
Same crash here, but 1.10.2. Config file:

```
discordchat {
    commands {
        permission {
            commands=global
            exec=admin
            help=global
            online=global
            permission=global
            reload=admin
            roleid=global
            setPermission=admin
            tps=global
            unstick=approved
        }
        prefix="!"
    }
    discord {
        channel="modded"
        server="251884253854302208"
        token="tHisIsNOtMyREaLToKENbUTYoUJuSTWAStedALoNGTiMETRyINgtoreADiT"
    }
    format {
        # Format for a player achievement message from MC to Discord.
        # $1 will be replaced with the player's username and $2 will be replaced with the achievement
        achievement="MC » $1 has just earned the achievement $2"
        # Format for a player death message from MC to Discord.
        # $1 will be replaced with the player's username and $2 will be replaced with the death message
        death="MC » $2"
        # Format for a normal message from Discord to MC.
        # $1 will be replaced with the channel, $2 will be replaced with the sender's username, and $3 will be replaced with the message
        fromDiscord="#$1 » <$2> $3"
        # Format for a normal message from MC to Discord.
        # $1 will be replaced with the sender's username and $2 will be replaced with the message
        fromMC="MC » <$1> $2"
        # Format for a player join message from MC to Discord.
        # $1 will be replaced with the player's username
        join="MC » $1 joined the game"
        # Format for a player leave message from MC to Discord.
        # $1 will be replaced with the player's username
        leave="MC » $1 left the game"
    }
    relay {
        achievements=true
        deaths=true
        joinleave=true
    }
}
```

The line that is crashing is [here](https://github.com/shadowfacts/DiscordChat/blob/rewrite/core/src/main/java/net/shadowfacts/discordchat/core/DiscordChat.java#L190). Looks like the list of channels itself is null–that's really weird. I tried the channel name both with and without the `#`, neither worked. On thing of note is that I run two servers (vanilla and modded) and I have a (Sponge) discord plugin running on the same account (same server, different channel). Not sure if that would be the issue.

**Comment by shadowfacts** [comment]
@Gaelan Are you using DiscordChat 2.0.1 (on CurseForge) or 2.0.2 (not on CurseForge)? In 2.0.1 the line that crashes is actually the line immediately before that, the one referencing the JDA object.

**Comment by Gaelan** [comment]
2.0.1. Good catch.

**Comment by Gaelan** [comment]
Looks like `serverStarted` is calling `sendMessage` before the `connect` thread finishes. This would explain the "works on my machine" stuff: it may or may not work depending on the server's internet speed vs. speed of CPU.
