### ISSUE TITLE
Server crashing on load

### ISSUE THREAD

**Issue by rileedeadeye** [shadowfacts/DiscordChat#66]
Brief explanation of issue: Server crashes on load

Steps to reproduce: Simply put mod in mod folder and load the server.

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/rileedeadeye/aeadfa6175dcfc2f297a341e84979862#file-gistfile1-txt

DiscordChat version:
DiscordChat-1.11-2.0.1.jar

Minecraft version:
1.11

**Comment by shadowfacts** [comment]
Can you send me a pastebin of your config with the token removed?
