### ISSUE TITLE
Outbound chat from MC -> discord stops syncing.

### ISSUE THREAD

**Issue by tomaste** [shadowfacts/DiscordChat#68]
Brief explanation of issue:
Outbound chat from MC -> discord stops syncing.

Steps to reproduce:

- Step 1
boot SF3 (stock) server.
- Step 2
Wait 5-10 mins

Link to crash report/log in a [gist](https://gist.github.com):  there is no crash, but this error shows in the logs:  https://gist.github.com/tomaste/e5d0ce4f1edcf37b494ae77b81aabe35

DiscordChat version:  DiscordChat-1.10.2-2.0.3.jar

Minecraft version: 1.10.2  (Skyfactory 3 stock server)

**Comment by Boomflex** [comment]
Can confirm this is for 1.11.2 also Shadow.

**Comment by tomaste** [comment]
One additional bit of info.  Chat from Discord to MC does continue to be passed into the MC server, just not the other direction.

**Comment by Krysinski** [comment]
We have same problem: one way chat, from Discord to MC after some time. And we found that token at BOT has changed automaticaly.
Half part of token has changing in BOT each time site reloads in browser, this not a bug.
no crash and some errors in console:
https://gist.github.com/Krysinski/7635ae823850d3f57d2ca243fc15d9ea
After server restart all works again.
server core: Thermos-1.7.10-1614-56

**Comment by ikkerens** [comment]
Can confirm, this also occurs on 1.7.10

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4
