### ISSUE TITLE
Minecraft Server Crashes after installation from DiscordChat

### ISSUE THREAD

**Issue by svalcken** [shadowfacts/DiscordChat#69]
Brief explanation of issue:
Server Crash after installation and Configuration.

befor i set in the config the right value (Token/Server and Channel) the Server starts and have logentrys from discordchat mod. Now i have added the values and after restart the server crashes.

Steps to reproduce:

befor i set in the config the right value (Token/Server and Channel) the Server starts and have logentrys from discordchat mod. Now i have added the values and after restart the server crashes.

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/svalcken/14a3ba59bca3d16de47dce9ef33e079e

DiscordChat version:
2.0.0 and 2.0.3
Minecraft version:
1.7.10

**Comment by svalcken** [comment]
Same problem on a clean installation of an Minecraft 1.7.10 with forge 10.13.4.1614.

I see also the configfile will be changed and any values now without ". Permission values, channel value.

i have added in same gist the Crash-Report of the clean instance.

**Comment by svalcken** [comment]
Problem found.
i have an invalid server id set and then crash the mod the server. Possible to add errorhandling and output bad connectionparameter. thanks

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4
