### ISSUE TITLE
Joining / leaving, Deaths, Achievements. Possible to add?

### ISSUE THREAD

**Issue by canilsen** [shadowfacts/DiscordChat#7]
Hey. Just curious of you could be able to make Discord show the info lines too.
Like Players joining and leaving, deaths, achievements etc. 

Perhaps make then individually toggleable in config.

**Comment by shadowfacts** [comment]
These will be possible in the 1.8.9 version, however likely not in the 1.7.10 version. This will require a pull request to Forge to add a specific event, and Forge for 1.7.10 isn't being updated anymore except for critical bug fixes.

**Comment by canilsen** [comment]
https://github.com/blay09/EiraIRC/tree/mc1710

Could this help you in any way? I'm pretty sure EiraIRC shows players joining and leaving etc.

It also adds a .list command wich could also be nice for Discord. Letting people do !list or something and have DiscordChat report who is online. (not showing the !list etc on the server for spam reasons)

**Comment by shadowfacts** [comment]
I suppose I could listen on those events manually...

**Comment by shadowfacts** [comment]
Available for 1.7.10 in DiscordChat 0.2.0.

**Comment by canilsen** [comment]
Very impressive!
