### ISSUE TITLE
[1.10.2]"Server is still starting, please reconnect error" caused by discord mod

### ISSUE THREAD

**Issue by Lyl4c** [shadowfacts/DiscordChat#70]
This one took me a while to find. My server kept capping out at 100% cpu usage and gave the "server is starting" error upon trying to connect to it via the client. After the server loads all the way it stays in this state forever until I stop it. 
I had to remove some mods from the server a bit at a time to find the mod causing the problem, and even tested the mod pack without the discord mod.  

Steps to reproduce:
1 setup a forge 12.18.3.2185 minecraft server
2 install discordchat v2.0.3
3 further setup discord config after starting the server once to create said config ;I
4 start server and wait until server fully loads

[Server Log](http://pastebin.com/UzAnbJnK)
starts around here methinks?: 
[01:33:34] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStartingEvent to mod mcp

Minecraft 1.10.2
Forge 12.18.3.2185
DiscordChat 2.0.3

**Comment by shadowfacts** [comment]
Should be fixed by 3dba4f35b15698fc90a5d37fefec0343498a00a3.

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4
