### ISSUE TITLE
[Critical bug] Server keeps on 100%+ CPU with new version of DiscordChat

### ISSUE THREAD

**Issue by hanakocz** [shadowfacts/DiscordChat#72]
Hi, I just updated to new version of DiscordChat from 0.3.0 for 1.7.10 (Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10, Java 8) to 2.0.3, all works perfectly after setting new version of config, only DiscordChat sucks all CPU even when server does nothing (no players, etc)

The bot is connected correctly to a server & channel and all works perfectly, only CPU is heavily overloaded.

![screenshot 2017-01-07 00 37 01](https://cloud.githubusercontent.com/assets/8724169/21736730/18e6675a-d473-11e6-9705-04a77c7310c2.png)
Midnight was the time when I updated the bot:
![221069_cpu-day](https://cloud.githubusercontent.com/assets/8724169/21739104/0baa571c-d492-11e6-8664-340c6648dde6.png)

PS: If bot not setupped, server keeps in not finished load and CPU usage is even bigger (did not made measurement then, though)

**Comment by ikkerens** [comment]
Having just looked through the code, this behaviour is correct it shouldn't impact your players too much unless you are running a low-core system.

Regardless, it is a bug. @shadowfacts, you are using LinkedBlockingQueue#take() in your sending queue which does not block, which causes your while(true) loop to run without limit. May I suggest using LinkedBlockingQueue#poll() instead which DOES block?

**Comment by shadowfacts** [comment]
Fixed in DiscordChat 2.0.4
