### ISSUE TITLE
[1.11.2]Crash on Startup

### ISSUE THREAD

**Issue by DoughnutDev** [shadowfacts/DiscordChat#76]
Brief explanation of issue: I installed the mod and started the server and it crashes and says that there are to DiscordChat jars but there isn't.

Steps to reproduce:

Put in the mods folder

Link to crash report/log in a [gist](https://gist.github.com):    https://gist.github.com/DoughnutDev/1ac074b857ccb2929bb0876cb07d00dc

DiscordChat version: 2.0.4

Minecraft version: 1.11.2

**Comment by shadowfacts** [comment]
Are you sure? Check mods/ and mods/1.11.2

**Comment by DoughnutDev** [comment]
There is only one in mods and there is no 1.11.2 folder.

**Comment by aschmois** [comment]
Yeah same thing is happening to me.

**Comment by shortybsd** [comment]
Minecraft 1.11.2
Forge 2223
DiscordChat-1.11.2-2.0.4

I get the same exact error, no double versions. No mods/1.11.2. Wiped/moved shadowfacts config folder. Still no luck.

**Comment by aschmois** [comment]
Any word on this issue? I've tried rebuilding from scratch but it keeps happening.

**Comment by shadowfacts** [comment]
No, sorry. I have no idea why this is happening and by all means this should be impossible (unless of course, there are actually 2 DiscordChat jars present).

**Comment by DoughnutDev** [comment]
Are you able to recreate this @shadowfacts ?

**Comment by aschmois** [comment]
Could there be duplicated classes in the jar file?

**Comment by kreezxil** [comment]
I just installed discord chat and immediately it complains about multiple entries with the same keys. I have only one copy of the mod installed. But the log shows two. It's as if you erroneously packed to instances of the build into the same jar, or the lastest builds of 1.11.2 is misintreprinting one your methods and spawning the jar again.

Issue:  1.11.2-2.0.4 crashes dedicated Forge 1.11.2 build 2226 on startup

Notes:
     the log shows there are 2 discord instance, however there is only one discord mod

crash report:
https://gist.github.com/44cee6e3ceae14c7af26ec46af9f2d4f

fml server latest:
https://gist.github.com/684b44143b8e0f56abec9e145a9811af

my mod list:
https://gist.github.com/ec309358b47fb73afa4dd5a0e701c3c0

**Comment by ProsperCraft** [comment]
We are having the same problem- 

https://gist.github.com/ProsperCraft/d3791f0a4f785c03f1bf9404984f87fc

**Comment by aschmois** [comment]
@shadowfacts took me a while to find it, but you are packaging OneElevenTwoMod.class and OneElevenMod.class

**Comment by aschmois** [comment]
For those wanting a fix, go into the jar file with a zip utility and delete the OneElevenMod.class inside net/shadowfacts/discordchat/one_eleven

**Comment by shortybsd** [comment]
@aschmois You sir, are awesome. Thank you kindly!

**Comment by kreezxil** [comment]
We followed aschmois instructions and managed to get this error: http://paste.fedoraproject.org/541324/14858225/

**Comment by DoughnutDev** [comment]
Says no such channel the channel number you entered is wrong in the config.

**Comment by shadowfacts** [comment]
Fixed. The version number hasn't changed, but the fixed version has replaced the broken one on the GH releases page and to CurseForge.
