### ISSUE TITLE
Discord to MC formatting

### ISSUE THREAD

**Issue by JasonMcRay** [shadowfacts/DiscordChat#77]
Brief explanation of issue:
- I am trying to use a formatting for the chat, so when the chat in minecraft is for example colored when spoken from Discord, but I am running into an issue. The § symbol to assign the formatting is being turned into ? (both after config reload using !reload from discord or restarting server)

Link to crash report/log in a [gist](https://gist.github.com):
NONE
DiscordChat version:
2.0.4
Minecraft version:
1.7.10

**Comment by ChromeDemonxXx** [comment]
+1, Getting this same issue.

**Comment by shadowfacts** [comment]
What do you mean? Are you using § one of the formats in the config (if so, which one?), in a Discord message, or in an MC chat message?

**Comment by shadowfacts** [comment]
Closing due to lack of response and that I can't reproduce this.
