### ISSUE TITLE
Is there a way to add the bot to multiple channels?

### ISSUE THREAD

**Issue by hmedway** [shadowfacts/DiscordChat#78]
Can I add the bot to multiple channels, if yes, please add it to the rtfm manual, otherwise, would you add it?

**Comment by shadowfacts** [comment]
No, it only supports connecting to one channel. Why do you need multiple?

**Comment by hmedway** [comment]
I wanted to split out my use of admin console commands from the main channel, which would only relay server chat and deaths.  

I know unprivileged roles aren't allowed to run commands I don't allow in the permmisions file, but from a tidiness perspective, I'd prefer to split them.  So I guess the is an enhancement request of low priority.

Thanks for the reply!
