### ISSUE TITLE
Anything put in the discord channel does not go to minecraft.

### ISSUE THREAD

**Issue by elsing** [shadowfacts/DiscordChat#79]
Hello,

Brief explanation of issue: When I type in the channel assigned to the server, it does not put anything in the server's chat. 

DiscordChat version: 2.0.4

Minecraft version: 1.7.10

Thanks,

Elliot

**Comment by shadowfacts** [comment]
Please post the log.

**Comment by elsing** [comment]
Which one exactly? There is no crash or anything.

**Comment by shadowfacts** [comment]
The FML latest log from the `logs/` directory.

**Comment by shadowfacts** [comment]
Closing due to lack of response.
