### ISSUE TITLE
Discord service itself having issues seems to cause issues with this mod

### ISSUE THREAD

**Issue by cha0s** [shadowfacts/DiscordChat#81]
## Brief explanation of issue:

Today, Discord seemed to lag out a bit/not show messages from people. When this happened, the entire server crashed, and then was unable to come back up, hanging on "Server is still starting".

## Steps to reproduce:

This is challenging to really spell out. It did seem to be happening up until I just now disabled the plugin, so maybe you'll have a window to try it in the immediate future. I know, that's a crappy ask. It's fundamentally a Discord issue, but it seems this plugin is not properly handling failure on Discord's end.

## Link to crash report/log in a [gist](https://gist.github.com):

https://gist.github.com/cha0s/8f104536183e037336c2061d72adfe09

## DiscordChat version:

1.10.2-2.0.4

## Minecraft version:

1.10.2, currently running Direwolf20 v1.7.0

**Comment by hanakocz** [comment]
I second this, for 1.7.10 it also has really bad outcomes, however server succesfully started after crash, when player sent a message. If needed I can put here crashes & errors from console after reboot. Probably would be useful to have some console command to put bot into offline state (for example when outages are or one wants to send some messages discretely to whole server without history on discord xD )

**Comment by cha0s** [comment]
Just for posterity, Discord had a rough day today: https://status.discordapp.com/incidents/dj3l6lw926kl

**Comment by Puremin0rez** [comment]
While this may be "discords fault", a single mod certainly shouldn't be deadlocking the server upon being unable to connect to discords API services. Hopefully this can be resolved correctly.

**Comment by shadowfacts** [comment]
Can you post the beginning of the FML log?

**Comment by OrdinatorStouff** [comment]
We had this problem affecting the official ATM:Expert server yesterday too. If it's of any help, this should be a full fml-server log from when we were affected by it from the archived logs: http://pastebin.com/p7cDs6WQ
