### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by cortus** [shadowfacts/DiscordChat#84]
Brief explanation of issue:  First off, I'm not the best at interpreting crash logs.  So, after adding the mod to the minecraft server, it crashes before it can fully load.  Not quite sure what is causing it, so I'll just attach a paste of the crash log on here.

Steps to reproduce:

- Step 1
- Step 2

Link to crash report/log in a [gist](https://gist.github.com): https://gist.github.com/cortus/cfae68063e93e0075f3ba95f5c6bcb81

DiscordChat version: DiscordChat-1.10.2-2.0.4

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
This isn't possible unless you've got a broken installation of Forge, as it automatically includes the Typesafe Config library. Try reinstalling forge and make sure the log file mentions "Downloading library com.typesafe:config".
