### ISSUE TITLE
Allow messaging (/tell) through the bot

### ISSUE THREAD

**Issue by Forecaster** [shadowfacts/DiscordChat#85]
By messaging the bot on discord something like
`Forecaster: Hello!`
It should send a tell in-game to "Forecaster" with the message, and you might be able to have a reply command in-game that lets you tell users on discord, causing the bot to send them a message with your reply.

This was requested by a user on our server.

**Comment by shadowfacts** [comment]
It'd probably be a command from Discord as well (e.g. `!tell Forecaster Hello`).

**Comment by Forecaster** [comment]
You'd have to enable sending the bot commands via pm then, otherwise it kind of defeats the purpose :P
