### ISSUE TITLE
Allow whitelisting/blacklisting prefixes

### ISSUE THREAD

**Issue by Forecaster** [shadowfacts/DiscordChat#86]
No idea how feasible this is, but we use ConventionalChat (http://files.vex.tty.sh/Conventional/dev/ConventionalChat-1.10.2-0.0.2.jar) by @Vexatos which makes default chat local (messages are only seen if you are within x blocks of sender) and adds shouting:
`!This is a shout`
Which are global. But currently DiscordChat sends all of these messages to Discord, but we'd like it to only send shouts and ignore local messages.

**Comment by Vexatos** [comment]
How about two config options: One to enable this feature (either as a whitelist or blacklist) and another one specifying the prefix and everything that's not starting with that prefix (or only that) will be filtered out. Maybe also remove the prefix from the message.

**Comment by Forecaster** [comment]
According to Vexatos DiscordChat gets the messages before CC does, so all that is needed to only send shouts would be to only send messages that start with an exclamation mark, but probably want to make it configurable so any one or more characters can be added.
