### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by MatthewKreuz** [shadowfacts/DiscordChat#88]
Brief explanation of issue:

Steps to reproduce:

- Put the config in "config\shadowfacts\DiscordChat\DiscordChat.conf
- Start the server.

https://gist.github.com/MatthewKreuz/2f9247b65f1076e3fbdd8c419ea04187

DiscordChat version:
DiscordChat-1.7.10-2.0.4
Minecraft version:
1.7.10
Can someone help me with photos or video of how to configure..
I'm trying but only receiving error.

**Comment by shadowfacts** [comment]
You shouldn't be using a numeric ID for the channel, use the name (all lowercase and without the `#`).

**Comment by MatthewKreuz** [comment]
Thanks
