### ISSUE TITLE
Discord crash with KCauldron

### ISSUE THREAD

**Issue by matthew-goodman** [shadowfacts/DiscordChat#9]
Hi, 

Just checking to see if KCauldron is supported, i keep getting the server crashing with the attached 

Kcauldron version is 1.7.10-1448.133

[crash-2016-01-22_21.04.42-server.txt](https://github.com/shadowfacts/DiscordChat/files/101442/crash-2016-01-22_21.04.42-server.txt)

Thanks
Matthew

**Comment by shadowfacts** [comment]
KCauldron should be supported. The crash is because you don't have Java 8 installed.
