### ISSUE TITLE
server crashes when loading mod at startup

### ISSUE THREAD

**Issue by imxLucid** [shadowfacts/DiscordChat#91]
server crashes when loading mod at startup

Steps to reproduce:
minecraft 1.12
forge-1.12-14.21.0.2340-universal.jar
DiscordChat-1.12-2.1.0.jar

downlaoded from:
https://minecraft.curseforge.com/projects/discordchat

setup using guide : 
https://rtfm.shadowfacts.net/discord-chat/setup/

starting minecraft server after mod setup produces error
logs = https://pastebin.com/ymL8VcHW

**Comment by shadowfacts** [comment]
Fixed in 2.1.1 (currently pending approval on CF)

**Comment by FiveEYZ** [comment]
nice, i was just searching for just this issue but for 1.10.2 xD
