### ISSUE TITLE
Addition of DiscordChat Bot Sends Server into Reboot Loop

### ISSUE THREAD

**Issue by janagyjr** [shadowfacts/DiscordChat#92]
Brief explanation of issue: Adding in DiscordChat to an existing 1.7.10 custom modded server

Steps to reproduce:

- Step 1
Install modded server
- Step 2
Install discord chat bot
-Step 3
restart server to generate config file
-Step 4
restart server for configs to take effect
-Step 5
infinite restart loop

Link to crash report/log in a [gist](https://gist.github.com):
https://gist.github.com/janagyjr/481de0056726518f28020c4ee87e64be

No crash-report to copy/pasta from, only the log file.
DiscordChat version:
1.7.10-2.1.1

Minecraft version:
1.7.10 

Forge version:
10.13.4.1614

**Comment by shadowfacts** [comment]
Did you even read the crash message? DiscordChat is misconfigured, the channel `tcg_joe-personalpack` doesn't exist.

**Comment by janagyjr** [comment]
The hell it doesn't. I set up the channel before I even downloaded the bot

![image](https://user-images.githubusercontent.com/23646259/27449468-23a66c2c-574e-11e7-882f-c2f10d047ece.png)
.

**Comment by shadowfacts** [comment]
Upload a screenshot of your Discord serve with the channels list.

**Comment by janagyjr** [comment]
I just did....

Also, I got the bot working now (mischecked an option on the Discord side of things), BUT...it's not relaying messages.

**Comment by janagyjr** [comment]
It is not relaying messages. I've got everything set up as mentioned in https://rtfm.shadowfacts.net/discord-chat/setup/ yet nothing is being relayed.

**Comment by shadowfacts** [comment]
Huh, the screenshot wasn't loading before.

Post the new log.

**Comment by janagyjr** [comment]
![image](https://user-images.githubusercontent.com/23646259/27490656-bacf3a1e-5804-11e7-8de9-06b7517ea1f4.png)

https://gist.github.com/janagyjr/cd93588f3f63819124ee73d823172f15

Logs taken right after test messages sent.

Edit: https://gist.github.com/janagyjr/21733740e4ed3e252b733c6595526dde

The other one doesn't show the sending of my test msg.

**Comment by shadowfacts** [comment]
That log doesn't show DiscordChat as even being loaded. There's no mention of it in the log.

**Comment by janagyjr** [comment]
I'm sorry to have been such a bother. I'm an idiot. I forgot I removed discordbot from the server until I could figure out the issue making the server go into a restart loop. Readded, restarted, working. Please, just shoot me now.

**Comment by shadowfacts** [comment]
Hah, I'm glad you've got it working.
