### ISSUE TITLE
discordchat still not working

### ISSUE THREAD

**Issue by imxLucid** [shadowfacts/DiscordChat#93]
Brief explanation of issue:
minecraft server doesnt start do to discordchat mod causing crash

LOG:
https://pastebin.com/yHPM0pZi

DiscordChat version:
DiscordChat-1.10.2-2.1.1
Minecraft version:
forge-1.12-14.21.0.2340-universal.jar

**Comment by djoveryde** [comment]
Not sure but looks like you may be missing the "/libraries" repo. If its not there then its unlikely anything will load correctly as most mods require the repo in order to load up. 

"NFO] [FML]: Failed to find the specified repository root C:/Users/Jt/Desktop/New folder/libraries"

**Comment by MinecraftXwinP** [comment]
Does DiscordChat-1.10.2 support Minecraft 1.12? According to the provided log,the server version is 1.12.
Maybe try to use DiscordChat-1.12.
