### ISSUE TITLE
Chat minecraft to discord

### ISSUE THREAD

**Issue by kiruaa** [shadowfacts/DiscordChat#94]
Brief explanation of issue:

Hello, I use the version DiscordChat-1.10.2-2.1.1 in the server FTB  and I encounter the following problem. If I write on discord, this is well relayed on Minecraft. But if I write on minecraft, this is not passed on to discord. Would I miss a step?
Thank you in advance for your return
cordially
Fabian

DiscordChat version: DiscordChat-1.10.2-2.1.1

Minecraft version: 1.10.2

**Comment by shadowfacts** [comment]
Is the prefix/suffix filter in the config enabled? Are you using any other mods that mess with chat?

**Comment by kiruaa** [comment]
My bad sry ! I just restart the server and it's ok :)
