### ISSUE TITLE
1.7.10 version lacks environment variables lookup support

### ISSUE THREAD

**Issue by OvermindDL1** [shadowfacts/DiscordChat#97]
With some notable modpacks the token keeps getting committed with the pack for the server, so they have to change it again a random people get in.

If possible, it would be convenient to have an option in the config to grab the discord token/channel/server ID's from the system environment variables instead of the config, and if they do not exist then no connection is attempted (except perhaps a log entry saying as much to the chat and/or first player join on a server).  This would prevent secrets from being accidentally added to packs.

**Comment by shadowfacts** [comment]
Information about how this works from the extended commit message:

> Lookup will be performed if the value in the config is empty.
The first fallback is the property (discordchat.token, discordchat.server, discordchat.channels) which is set with the -Ddiscordchat.server=... VM argument.
The second fallback (if no property value is provided) is the environment variable (DISCORDCHAT_TOKEN, etc.) which is specified though the command line prior to launching the server.
