### ISSUE TITLE
Unable to complete setup of mod due to bot not accepting initial !roleid command

### ISSUE THREAD

**Issue by sharkck** [shadowfacts/DiscordChat#99]
Brief explanation of issue:
Unable to set a role per instructions from curse page.

Steps to reproduce:
Add mod to 'mods' folder on server
Run server once
Modify config file with server/channel/token information
In Discord channel, type !roleid Supreme Overlord (Or anything else)
Get response: 
"Minecraft BridgeBOT - Today at 3:18 AM
No such role: Supreme Overlord"

Expected Response: What is shown on the instructions on the page (https://rtfm.shadowfacts.net/discord-chat/info/)

Link to crash report/log in a [gist](https://gist.github.com):

No crash report

DiscordChat version: Current (DiscordChat-1.12-2.2.0.jar)

Minecraft version: Current (MCForge 14.21.1.2443)

**Comment by shadowfacts** [comment]
Works fine for me.

![screen shot 2017-10-08 at 3 07 28 pm](https://user-images.githubusercontent.com/7091588/31319960-6a194b8e-ac3a-11e7-803a-a286fe320db4.png)

**Comment by GabrielSieben** [comment]
I am having the same problem @shadowfacts . :(

**Comment by GabrielSieben** [comment]
Okay solved. Apparently, by roles it uses _Discord Roles_... So, if you want one person to have admin powers, you make a Discord role, get it's ID, and then add it into `permissions.json`. Could perhaps be clarified...
